/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as BancoColaboradoresRouteImport } from './routes/banco-colaboradores'
import { Route as BancoDadosRouteImport } from './routes/banco-dados'
import { Route as BloqueiosRouteImport } from './routes/bloqueios'
import { Route as CadastroDiariasRouteImport } from './routes/cadastro-diarias'
import { Route as CandidatosRouteImport } from './routes/candidatos'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConfirmacoesRouteImport } from './routes/confirmacoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MinhaProgramacaoRouteImport } from './routes/minha-programacao'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ProgramadorasRouteImport } from './routes/programadoras'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SaudeSistemaRouteImport } from './routes/saude-sistema'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as ColaboradoresIndexRouteImport } from './routes/colaboradores.index'
import { Route as ColaboradoresNomeRouteImport } from './routes/colaboradores.$nome'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasNomeRouteImport } from './routes/empresas.$nome'
import { Route as RsCandidatosRouteImport } from './routes/rs.candidatos'
import { Route as RsDashboardRouteImport } from './routes/rs.dashboard'
import { Route as RsEmpresasRouteImport } from './routes/rs.empresas'
import { Route as RsLevantamentoRouteImport } from './routes/rs.levantamento'
import { Route as ApiPublicHooksBackupAgendadoRouteImport } from './routes/api/public/hooks/backup-agendado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoColaboradoresRoute = BancoColaboradoresRouteImport.update({
  id: '/banco-colaboradores',
  path: '/banco-colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoDadosRoute = BancoDadosRouteImport.update({
  id: '/banco-dados',
  path: '/banco-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueiosRoute = BloqueiosRouteImport.update({
  id: '/bloqueios',
  path: '/bloqueios',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroDiariasRoute = CadastroDiariasRouteImport.update({
  id: '/cadastro-diarias',
  path: '/cadastro-diarias',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatosRoute = CandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacoesRoute = ConfirmacoesRouteImport.update({
  id: '/confirmacoes',
  path: '/confirmacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaProgramacaoRoute = MinhaProgramacaoRouteImport.update({
  id: '/minha-programacao',
  path: '/minha-programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramadorasRoute = ProgramadorasRouteImport.update({
  id: '/programadoras',
  path: '/programadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeSistemaRoute = SaudeSistemaRouteImport.update({
  id: '/saude-sistema',
  path: '/saude-sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresIndexRoute = ColaboradoresIndexRouteImport.update({
  id: '/colaboradores/',
  path: '/colaboradores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresNomeRoute = ColaboradoresNomeRouteImport.update({
  id: '/colaboradores/$nome',
  path: '/colaboradores/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasNomeRoute = EmpresasNomeRouteImport.update({
  id: '/empresas/$nome',
  path: '/empresas/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const RsCandidatosRoute = RsCandidatosRouteImport.update({
  id: '/rs/candidatos',
  path: '/rs/candidatos',
  getParentRoute: () => rootRouteImport,
} as any)
const RsDashboardRoute = RsDashboardRouteImport.update({
  id: '/rs/dashboard',
  path: '/rs/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RsEmpresasRoute = RsEmpresasRouteImport.update({
  id: '/rs/empresas',
  path: '/rs/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const RsLevantamentoRoute = RsLevantamentoRouteImport.update({
  id: '/rs/levantamento',
  path: '/rs/levantamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackupAgendadoRoute =
  ApiPublicHooksBackupAgendadoRouteImport.update({
    id: '/api/public/hooks/backup-agendado',
    path: '/api/public/hooks/backup-agendado',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/administracao': typeof AdministracaoRoute
  '/analise': typeof AnaliseRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/banco-colaboradores': typeof BancoColaboradoresRoute
  '/banco-dados': typeof BancoDadosRoute
  '/bloqueios': typeof BloqueiosRoute
  '/cadastro-diarias': typeof CadastroDiariasRoute
  '/candidatos': typeof CandidatosRoute
  '/chat': typeof ChatRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmacoes': typeof ConfirmacoesRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/metas': typeof MetasRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/perfis': typeof PerfisRoute
  '/performance': typeof PerformanceRoute
  '/programadoras': typeof ProgramadorasRoute
  '/radar': typeof RadarRoute
  '/relatorios': typeof RelatoriosRoute
  '/saude-sistema': typeof SaudeSistemaRoute
  '/vagas': typeof VagasRoute
  '/colaboradores/$nome': typeof ColaboradoresNomeRoute
  '/empresas/$nome': typeof EmpresasNomeRoute
  '/rs/candidatos': typeof RsCandidatosRoute
  '/rs/dashboard': typeof RsDashboardRoute
  '/rs/empresas': typeof RsEmpresasRoute
  '/rs/levantamento': typeof RsLevantamentoRoute
  '/colaboradores/': typeof ColaboradoresIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/api/public/hooks/backup-agendado': typeof ApiPublicHooksBackupAgendadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/administracao': typeof AdministracaoRoute
  '/analise': typeof AnaliseRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/banco-colaboradores': typeof BancoColaboradoresRoute
  '/banco-dados': typeof BancoDadosRoute
  '/bloqueios': typeof BloqueiosRoute
  '/cadastro-diarias': typeof CadastroDiariasRoute
  '/candidatos': typeof CandidatosRoute
  '/chat': typeof ChatRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmacoes': typeof ConfirmacoesRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/metas': typeof MetasRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/perfis': typeof PerfisRoute
  '/performance': typeof PerformanceRoute
  '/programadoras': typeof ProgramadorasRoute
  '/radar': typeof RadarRoute
  '/relatorios': typeof RelatoriosRoute
  '/saude-sistema': typeof SaudeSistemaRoute
  '/vagas': typeof VagasRoute
  '/colaboradores/$nome': typeof ColaboradoresNomeRoute
  '/empresas/$nome': typeof EmpresasNomeRoute
  '/rs/candidatos': typeof RsCandidatosRoute
  '/rs/dashboard': typeof RsDashboardRoute
  '/rs/empresas': typeof RsEmpresasRoute
  '/rs/levantamento': typeof RsLevantamentoRoute
  '/colaboradores': typeof ColaboradoresIndexRoute
  '/empresas': typeof EmpresasIndexRoute
  '/api/public/hooks/backup-agendado': typeof ApiPublicHooksBackupAgendadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/administracao': typeof AdministracaoRoute
  '/analise': typeof AnaliseRoute
  '/auditoria': typeof AuditoriaRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/banco-colaboradores': typeof BancoColaboradoresRoute
  '/banco-dados': typeof BancoDadosRoute
  '/bloqueios': typeof BloqueiosRoute
  '/cadastro-diarias': typeof CadastroDiariasRoute
  '/candidatos': typeof CandidatosRoute
  '/chat': typeof ChatRoute
  '/comparar': typeof CompararRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/confirmacoes': typeof ConfirmacoesRoute
  '/historico': typeof HistoricoRoute
  '/importar': typeof ImportarRoute
  '/metas': typeof MetasRoute
  '/minha-programacao': typeof MinhaProgramacaoRoute
  '/perfis': typeof PerfisRoute
  '/performance': typeof PerformanceRoute
  '/programadoras': typeof ProgramadorasRoute
  '/radar': typeof RadarRoute
  '/relatorios': typeof RelatoriosRoute
  '/saude-sistema': typeof SaudeSistemaRoute
  '/vagas': typeof VagasRoute
  '/colaboradores/$nome': typeof ColaboradoresNomeRoute
  '/empresas/$nome': typeof EmpresasNomeRoute
  '/rs/candidatos': typeof RsCandidatosRoute
  '/rs/dashboard': typeof RsDashboardRoute
  '/rs/empresas': typeof RsEmpresasRoute
  '/rs/levantamento': typeof RsLevantamentoRoute
  '/colaboradores/': typeof ColaboradoresIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/api/public/hooks/backup-agendado': typeof ApiPublicHooksBackupAgendadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/administracao'
    | '/analise'
    | '/auditoria'
    | '/auth'
    | '/backups'
    | '/banco-colaboradores'
    | '/banco-dados'
    | '/bloqueios'
    | '/cadastro-diarias'
    | '/candidatos'
    | '/chat'
    | '/comparar'
    | '/configuracoes'
    | '/confirmacoes'
    | '/historico'
    | '/importar'
    | '/metas'
    | '/minha-programacao'
    | '/perfis'
    | '/performance'
    | '/programadoras'
    | '/radar'
    | '/relatorios'
    | '/saude-sistema'
    | '/vagas'
    | '/colaboradores/$nome'
    | '/empresas/$nome'
    | '/rs/candidatos'
    | '/rs/dashboard'
    | '/rs/empresas'
    | '/rs/levantamento'
    | '/colaboradores/'
    | '/empresas/'
    | '/api/public/hooks/backup-agendado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/administracao'
    | '/analise'
    | '/auditoria'
    | '/auth'
    | '/backups'
    | '/banco-colaboradores'
    | '/banco-dados'
    | '/bloqueios'
    | '/cadastro-diarias'
    | '/candidatos'
    | '/chat'
    | '/comparar'
    | '/configuracoes'
    | '/confirmacoes'
    | '/historico'
    | '/importar'
    | '/metas'
    | '/minha-programacao'
    | '/perfis'
    | '/performance'
    | '/programadoras'
    | '/radar'
    | '/relatorios'
    | '/saude-sistema'
    | '/vagas'
    | '/colaboradores/$nome'
    | '/empresas/$nome'
    | '/rs/candidatos'
    | '/rs/dashboard'
    | '/rs/empresas'
    | '/rs/levantamento'
    | '/colaboradores'
    | '/empresas'
    | '/api/public/hooks/backup-agendado'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/administracao'
    | '/analise'
    | '/auditoria'
    | '/auth'
    | '/backups'
    | '/banco-colaboradores'
    | '/banco-dados'
    | '/bloqueios'
    | '/cadastro-diarias'
    | '/candidatos'
    | '/chat'
    | '/comparar'
    | '/configuracoes'
    | '/confirmacoes'
    | '/historico'
    | '/importar'
    | '/metas'
    | '/minha-programacao'
    | '/perfis'
    | '/performance'
    | '/programadoras'
    | '/radar'
    | '/relatorios'
    | '/saude-sistema'
    | '/vagas'
    | '/colaboradores/$nome'
    | '/empresas/$nome'
    | '/rs/candidatos'
    | '/rs/dashboard'
    | '/rs/empresas'
    | '/rs/levantamento'
    | '/colaboradores/'
    | '/empresas/'
    | '/api/public/hooks/backup-agendado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  AdministracaoRoute: typeof AdministracaoRoute
  AnaliseRoute: typeof AnaliseRoute
  AuditoriaRoute: typeof AuditoriaRoute
  AuthRoute: typeof AuthRoute
  BackupsRoute: typeof BackupsRoute
  BancoColaboradoresRoute: typeof BancoColaboradoresRoute
  BancoDadosRoute: typeof BancoDadosRoute
  BloqueiosRoute: typeof BloqueiosRoute
  CadastroDiariasRoute: typeof CadastroDiariasRoute
  CandidatosRoute: typeof CandidatosRoute
  ChatRoute: typeof ChatRoute
  CompararRoute: typeof CompararRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConfirmacoesRoute: typeof ConfirmacoesRoute
  HistoricoRoute: typeof HistoricoRoute
  ImportarRoute: typeof ImportarRoute
  MetasRoute: typeof MetasRoute
  MinhaProgramacaoRoute: typeof MinhaProgramacaoRoute
  PerfisRoute: typeof PerfisRoute
  PerformanceRoute: typeof PerformanceRoute
  ProgramadorasRoute: typeof ProgramadorasRoute
  RadarRoute: typeof RadarRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SaudeSistemaRoute: typeof SaudeSistemaRoute
  VagasRoute: typeof VagasRoute
  ColaboradoresNomeRoute: typeof ColaboradoresNomeRoute
  EmpresasNomeRoute: typeof EmpresasNomeRoute
  RsCandidatosRoute: typeof RsCandidatosRoute
  RsDashboardRoute: typeof RsDashboardRoute
  RsEmpresasRoute: typeof RsEmpresasRoute
  RsLevantamentoRoute: typeof RsLevantamentoRoute
  ColaboradoresIndexRoute: typeof ColaboradoresIndexRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
  ApiPublicHooksBackupAgendadoRoute: typeof ApiPublicHooksBackupAgendadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco-colaboradores': {
      id: '/banco-colaboradores'
      path: '/banco-colaboradores'
      fullPath: '/banco-colaboradores'
      preLoaderRoute: typeof BancoColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco-dados': {
      id: '/banco-dados'
      path: '/banco-dados'
      fullPath: '/banco-dados'
      preLoaderRoute: typeof BancoDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueios': {
      id: '/bloqueios'
      path: '/bloqueios'
      fullPath: '/bloqueios'
      preLoaderRoute: typeof BloqueiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-diarias': {
      id: '/cadastro-diarias'
      path: '/cadastro-diarias'
      fullPath: '/cadastro-diarias'
      preLoaderRoute: typeof CadastroDiariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatos': {
      id: '/candidatos'
      path: '/candidatos'
      fullPath: '/candidatos'
      preLoaderRoute: typeof CandidatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacoes': {
      id: '/confirmacoes'
      path: '/confirmacoes'
      fullPath: '/confirmacoes'
      preLoaderRoute: typeof ConfirmacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-programacao': {
      id: '/minha-programacao'
      path: '/minha-programacao'
      fullPath: '/minha-programacao'
      preLoaderRoute: typeof MinhaProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programadoras': {
      id: '/programadoras'
      path: '/programadoras'
      fullPath: '/programadoras'
      preLoaderRoute: typeof ProgramadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude-sistema': {
      id: '/saude-sistema'
      path: '/saude-sistema'
      fullPath: '/saude-sistema'
      preLoaderRoute: typeof SaudeSistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores/': {
      id: '/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof ColaboradoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores/$nome': {
      id: '/colaboradores/$nome'
      path: '/colaboradores/$nome'
      fullPath: '/colaboradores/$nome'
      preLoaderRoute: typeof ColaboradoresNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$nome': {
      id: '/empresas/$nome'
      path: '/empresas/$nome'
      fullPath: '/empresas/$nome'
      preLoaderRoute: typeof EmpresasNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/candidatos': {
      id: '/rs/candidatos'
      path: '/rs/candidatos'
      fullPath: '/rs/candidatos'
      preLoaderRoute: typeof RsCandidatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/dashboard': {
      id: '/rs/dashboard'
      path: '/rs/dashboard'
      fullPath: '/rs/dashboard'
      preLoaderRoute: typeof RsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/empresas': {
      id: '/rs/empresas'
      path: '/rs/empresas'
      fullPath: '/rs/empresas'
      preLoaderRoute: typeof RsEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/levantamento': {
      id: '/rs/levantamento'
      path: '/rs/levantamento'
      fullPath: '/rs/levantamento'
      preLoaderRoute: typeof RsLevantamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup-agendado': {
      id: '/api/public/hooks/backup-agendado'
      path: '/api/public/hooks/backup-agendado'
      fullPath: '/api/public/hooks/backup-agendado'
      preLoaderRoute: typeof ApiPublicHooksBackupAgendadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  AdministracaoRoute: AdministracaoRoute,
  AnaliseRoute: AnaliseRoute,
  AuditoriaRoute: AuditoriaRoute,
  AuthRoute: AuthRoute,
  BackupsRoute: BackupsRoute,
  BancoColaboradoresRoute: BancoColaboradoresRoute,
  BancoDadosRoute: BancoDadosRoute,
  BloqueiosRoute: BloqueiosRoute,
  CadastroDiariasRoute: CadastroDiariasRoute,
  CandidatosRoute: CandidatosRoute,
  ChatRoute: ChatRoute,
  CompararRoute: CompararRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConfirmacoesRoute: ConfirmacoesRoute,
  HistoricoRoute: HistoricoRoute,
  ImportarRoute: ImportarRoute,
  MetasRoute: MetasRoute,
  MinhaProgramacaoRoute: MinhaProgramacaoRoute,
  PerfisRoute: PerfisRoute,
  PerformanceRoute: PerformanceRoute,
  ProgramadorasRoute: ProgramadorasRoute,
  RadarRoute: RadarRoute,
  RelatoriosRoute: RelatoriosRoute,
  SaudeSistemaRoute: SaudeSistemaRoute,
  VagasRoute: VagasRoute,
  ColaboradoresNomeRoute: ColaboradoresNomeRoute,
  EmpresasNomeRoute: EmpresasNomeRoute,
  RsCandidatosRoute: RsCandidatosRoute,
  RsDashboardRoute: RsDashboardRoute,
  RsEmpresasRoute: RsEmpresasRoute,
  RsLevantamentoRoute: RsLevantamentoRoute,
  ColaboradoresIndexRoute: ColaboradoresIndexRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
  ApiPublicHooksBackupAgendadoRoute: ApiPublicHooksBackupAgendadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
